query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MYLK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K9'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('LATS2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PAK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('DYRK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAMK2B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MATK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP4K5'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CRK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK9'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PBK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ULK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('DDR2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('IKBKB'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RAF1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('AXIN1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PTK2B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAMK2D'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('EGFR'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK39'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('LIMK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RPS6KA3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CHUK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ARAF'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ZHX2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('WEE1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP4K4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MOK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK17'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('EEF2K'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CCND2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('LATS1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKCI'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('FES'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ILK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PLK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MARK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('WNK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PDPK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKDC'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('HIPK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PIKFYVE'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKACA'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CSNK2B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('AKT1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK33'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PASK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('AAK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('APC'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('IKBKG'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MARK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('HIPK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('NEK6'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PKD2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('HCK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('NEK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRPF4B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TNK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ZRANB2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDC42BPA'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('JAK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('HIPK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K11'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKAA2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('FGFR1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK11'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ABL1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ROCK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAMK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RIPK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('NRK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('FGFR3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TAOK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK5'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TGFBR2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKCD'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDKL5'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('NME1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MINK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MKNK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('DCLK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP2K7'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('AKT1S1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('WNK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BRSK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKAR2A'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SRC'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SRPK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RPS6KB2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKD3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('HIPK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PIK3CG'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BAZ1B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TYK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('EIF2AK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('NEK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RPTOR'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SMG1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CLK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SYK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RIPK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TRPM7'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BRAF'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK25'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAMK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ATR'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK12'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDC42BPG'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SIK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TAOK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RIOK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TTK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAD'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('GTF2F1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RIPK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MASTL'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP2K6'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K20'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK17A'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('EIF2AK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAMKK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CIT'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('KIT'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAPK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('OXSR1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('GRK6'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKAG2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('NEK9'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKD2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BMP2K'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK11A'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MNAT1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SGK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAPKAPK5'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKAB2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MTOR'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ATM'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKCQ'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PKN2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAMK2G'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PAK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BTK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CSNK1E'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAST1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SCYL3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BLVRA'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('NEK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK13'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('KSR1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TTBK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K8'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PI4K2A'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MARK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ABL2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PKMYT1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('GRK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKD1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RPS6KA4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('KRAS'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('IRAK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ROBO1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP2K2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK11B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CLK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PTK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TLK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKAR2B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CCNE2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K7'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKAB1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('WNK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RET'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TAOK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('EIF2AK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('GSK3A'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SIK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ERBB2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('GSK3B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BUB1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('EPHA1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAST2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('DYRK1A'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('HASPIN'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RICTOR'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BCKDK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RPS6KB1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('EPHB4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PIK3CD'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRR5'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP4K2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK16'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKAA1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CSNK1D'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BRD4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK10'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CCNE1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BMPR2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PRKCA'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RPS6KA6'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('DAPK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CAMKK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PKM'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TESK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('RPS6KA1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PAK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('BCR'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAP3K2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MAPK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MET'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('STK10'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SRPK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MELK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PGK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TTN'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SHB'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SHC1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('PKN1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('VRK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CLK4'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK18'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK7'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MARK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('DYRK1B'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TNIK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CDK14'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('MRE11'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('TLK2'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('ROBO3'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SNRK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('SLK'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CHEK1'),cell_line(c1))).
query(doesDinhibitKinC(perturbation('AZD1480'),kinase('CLK1'),cell_line(c1))).
