knownkinasetarget('SNF1', 'MIG1').
knownkinasetarget('CDC28', 'SWE1').
knownkinasetarget('SLT2', 'MKK2').
knownkinasetarget('CDC5', 'SWE1').
knownkinasetarget('HOG1', 'FPS1').
knownkinasetarget('PHO85', 'PHO80').
knownkinasetarget('PHO85', 'PHO81').
knownkinasetarget('PHO85', 'PHO4').
knownkinasetarget('SAK1', 'SNF1').
knownkinasetarget('PRK1', 'PAN1').
knownkinasetarget('MEC1', 'RFA1').
knownkinasetarget('CDC28', 'SIC1').
knownkinasetarget('CDC28', 'WHI5').
knownkinasetarget('RCK2', 'HOG1').
knownkinasetarget('HOG1', 'RCK2').
knownkinasetarget('HSL1', 'HSL7').
knownkinasetarget('SWE1', 'CDC28').
knownkinasetarget('CDC28', 'CDC5').
knownkinasetarget('CDC28', 'CDH1').
knownkinasetarget('RAD53', 'DUN1').
knownkinasetarget('TPK3', 'ATG1').
knownkinasetarget('CDC5', 'MCD1').
knownkinasetarget('MPS1', 'SPC42').
knownkinasetarget('PRK1', 'SLA1').
knownkinasetarget('PHO85', 'RVS167').
knownkinasetarget('YPD1', 'SSK1').
knownkinasetarget('CDC28', 'RGA2').
knownkinasetarget('SCH9', 'RIM15').
knownkinasetarget('BUD32', 'GRX4').
knownkinasetarget('TPK2', 'ATG1').
knownkinasetarget('TPK1', 'ATG1').
knownkinasetarget('CDC28', 'FKH2').
knownkinasetarget('PKH1', 'PIL1').
knownkinasetarget('CDC28', 'NET1').
knownkinasetarget('CDC28', 'NDD1').
knownkinasetarget('IPL1', 'SLI15').
knownkinasetarget('HOG1', 'SMP1').
knownkinasetarget('CDC28', 'FIN1').
knownkinasetarget('CDC5', 'RAD53').
knownkinasetarget('SLT2', 'MKK1').
knownkinasetarget('CDC28', 'CLN3').
knownkinasetarget('CAK1', 'CDC28').
knownkinasetarget('CDC28', 'PDS1').
knownkinasetarget('SLT2', 'RLM1').
knownkinasetarget('DUN1', 'SML1').
knownkinasetarget('CDC28', 'KAR9').
knownkinasetarget('CDC15', 'DBF2').
knownkinasetarget('KIN28', 'RPO21').
knownkinasetarget('PKH2', 'PIL1').
knownkinasetarget('CDC28', 'SHS1').
knownkinasetarget('RAD53', 'RAD9').
knownkinasetarget('SSN3', 'GAL4').
knownkinasetarget('PHO85', 'RGA2').
knownkinasetarget('ELM1', 'GIN4').
knownkinasetarget('TPK1', 'YAK1').
knownkinasetarget('YCK1', 'HEK2').
knownkinasetarget('SNF1', 'GAL83').
knownkinasetarget('PHO85', 'RIM15').
knownkinasetarget('KIN4', 'BFA1').
knownkinasetarget('BUB1', 'BUB3').
knownkinasetarget('PBS2', 'HOG1').
knownkinasetarget('KIC1', 'CBK1').
knownkinasetarget('SKY1', 'NPL3').
knownkinasetarget('SSN3', 'RPO21').
knownkinasetarget('CDC28', 'SLD2').
knownkinasetarget('HRR25', 'CRZ1').
knownkinasetarget('CDC28', 'CDC16').
knownkinasetarget('GIN4', 'SHS1').
knownkinasetarget('PBS2', 'SHO1').
knownkinasetarget('CLA4', 'SWE1').
knownkinasetarget('HOG1', 'SKO1').
knownkinasetarget('CDC28', 'ASK1').
knownkinasetarget('CBK1', 'SSD1').
knownkinasetarget('TPK2', 'BCY1').
knownkinasetarget('PHO85', 'BNI4').
knownkinasetarget('SGV1', 'RPO21').
knownkinasetarget('CDC28', 'VAC17').
knownkinasetarget('TPK1', 'CRZ1').
knownkinasetarget('CDC28', 'CDC6').
knownkinasetarget('PHO85', 'GSY2').
knownkinasetarget('SLT2', 'MSG5').
knownkinasetarget('CDC5', 'REC8').
knownkinasetarget('BUD32', 'KAE1').
knownkinasetarget('CKA2', 'SIC1').
knownkinasetarget('TPK1', 'BCY1').
knownkinasetarget('RIM11', 'IME1').
knownkinasetarget('CDC28', 'MCM3').
knownkinasetarget('TPK1', 'CDC20').
knownkinasetarget('TPK2', 'CDC20').
knownkinasetarget('SLT2', 'SIR3').
knownkinasetarget('RAD53', 'SWI6').
knownkinasetarget('CDC28', 'CDC27').
knownkinasetarget('SWE1', 'HSC82').
knownkinasetarget('SSN3', 'STE12').
knownkinasetarget('SLT2', 'SWI4').
knownkinasetarget('CDC28', 'BEM1').
knownkinasetarget('DBF2', 'MOB1').
knownkinasetarget('TOR1', 'ATG13').
knownkinasetarget('PHO85', 'PCL5').
knownkinasetarget('TPK2', 'SFL1').
knownkinasetarget('PKC1', 'BCK1').
knownkinasetarget('PKH2', 'LSP1').
knownkinasetarget('PKH1', 'LSP1').
knownkinasetarget('MEK1', 'RED1').
knownkinasetarget('IPL1', 'ASE1').
knownkinasetarget('MEC1', 'RAD53').
knownkinasetarget('CDC28', 'SPC110').
knownkinasetarget('CLA4', 'BEM1').
knownkinasetarget('TPK3', 'BCY1').
knownkinasetarget('SSK2', 'PBS2').
knownkinasetarget('CBK1', 'ACE2').
knownkinasetarget('SNF1', 'SIP1').
knownkinasetarget('CLA4', 'CDC12').
knownkinasetarget('CAK1', 'CTK1').
knownkinasetarget('TOR2', 'ATG13').
knownkinasetarget('HOG1', 'PBS2').
knownkinasetarget('ATG1', 'ATG17').
knownkinasetarget('PRK1', 'ABP1').
knownkinasetarget('HSL1', 'HOG1').
knownkinasetarget('HOG1', 'HSL1').
knownkinasetarget('BCK1', 'SLT2').
knownkinasetarget('PKH1', 'YPK1').
knownkinasetarget('CDC5', 'SPC72').
knownkinasetarget('CLA4', 'CDC10').
knownkinasetarget('CDC5', 'CDH1').
knownkinasetarget('CKA1', 'SGT1').
knownkinasetarget('CAK1', 'IME2').
knownkinasetarget('TPK3', 'RGT1').
knownkinasetarget('SNF1', 'REG1').
knownkinasetarget('CDC28', 'ORC6').
knownkinasetarget('DUN1', 'RAD53').
knownkinasetarget('CDC28', 'GIN4').
knownkinasetarget('CDC28', 'SPC42').
knownkinasetarget('CDC28', 'FAR1').
knownkinasetarget('SNF1', 'GLN3').
knownkinasetarget('HOG1', 'STE50').
knownkinasetarget('FPK1', 'YPK1').
knownkinasetarget('IME2', 'SIC1').
knownkinasetarget('MKK2', 'SLT2').
knownkinasetarget('SNF1', 'SIP4').
knownkinasetarget('SSN3', 'MED2').
knownkinasetarget('SNF1', 'SIP2').
knownkinasetarget('SLT2', 'SWI6').
knownkinasetarget('SAK1', 'GAL83').
knownkinasetarget('SKY1', 'GBP2').
knownkinasetarget('SGV1', 'SPT5').
knownkinasetarget('CAK1', 'KIN28').
knownkinasetarget('YPD1', 'SKN7').
knownkinasetarget('CDC28', 'CDC13').
knownkinasetarget('IME2', 'IME1').
knownkinasetarget('IPL1', 'MAD3').
knownkinasetarget('KIN28', 'MED4').
knownkinasetarget('CDC28', 'RAD53').
knownkinasetarget('CDC28', 'CDC23').
knownkinasetarget('MEK1', 'HOP1').
knownkinasetarget('CDC28', 'CLN1').
knownkinasetarget('CBK1', 'MOB2').
knownkinasetarget('SNF1', 'MIG3').
knownkinasetarget('CKA1', 'SIC1').
knownkinasetarget('CKA2', 'RIO1').
knownkinasetarget('SLN1', 'YPD1').
knownkinasetarget('YCK3', 'VPS41').
knownkinasetarget('SCH9', 'BUD32').
knownkinasetarget('SLT2', 'ROM2').
knownkinasetarget('CDC28', 'ACM1').
knownkinasetarget('PHO85', 'SHS1').
knownkinasetarget('FUS3', 'FAR1').
knownkinasetarget('CDC28', 'CLB2').
knownkinasetarget('TPK1', 'CDC25').
knownkinasetarget('KIC1', 'HYM1').
knownkinasetarget('SWE1', 'HSP82').
knownkinasetarget('CDC5', 'NET1').
knownkinasetarget('CDC5', 'NDD1').
knownkinasetarget('ATG1', 'ATG11').
knownkinasetarget('CDC28', 'CKS1').
knownkinasetarget('HOG1', 'SLT2').
knownkinasetarget('SSK2', 'HOG1').
knownkinasetarget('AKL1', 'SCD5').
knownkinasetarget('CDC28', 'CAK1').
knownkinasetarget('SNF1', 'SNF4').
knownkinasetarget('CDC5', 'BFA1').
knownkinasetarget('YAK1', 'POP2').
knownkinasetarget('YPK1', 'FPK1').
knownkinasetarget('HOG1', 'NHA1').
knownkinasetarget('SLT2', 'BCK1').
knownkinasetarget('CLA4', 'CDC24').
knownkinasetarget('CDC5', 'CDC14').
knownkinasetarget('RIM11', 'UME6').
knownkinasetarget('ELM1', 'SNF1').
knownkinasetarget('PHO85', 'GCN4').
knownkinasetarget('CKA1', 'ELF1').
knownkinasetarget('MPS1', 'SPC110').
knownkinasetarget('HOG1', 'SIC1').
knownkinasetarget('CKA1', 'PUF6').
knownkinasetarget('CDC28', 'TUS1').
knownkinasetarget('CAK1', 'SGV1').
knownkinasetarget('CDC5', 'DBF2').
knownkinasetarget('CDC28', 'ORC2').
knownkinasetarget('CDC28', 'TGL4').
knownkinasetarget('MKK1', 'SLT2').
knownkinasetarget('CDC28', 'LTE1').
knownkinasetarget('TPK1', 'BMH1').
knownkinasetarget('CDC28', 'SWI4').
knownkinasetarget('CDC5', 'DBF4').
knownkinasetarget('CDC28', 'SWI6').
knownkinasetarget('CLA4', 'CDC42').
knownkinasetarget('PBS2', 'SSK2').
knownkinasetarget('GIN4', 'CDC12').
knownkinasetarget('SSK2', 'SSK1').
knownkinasetarget('MCK1', 'CDC19').
knownkinasetarget('PHO85', 'SIC1').
knownkinasetarget('CLA4', 'CDC11').
knownkinasetarget('KIN28', 'CCL1').
knownkinasetarget('MCK1', 'BCY1').
knownkinasetarget('CDC5', 'BRN1').
knownkinasetarget('CDC5', 'YCG1').
knownkinasetarget('CDC5', 'YCS4').
knownkinasetarget('STE7', 'FUS3').
knownkinasetarget('FUS3', 'STE7').
knownkinasetarget('PRK1', 'SCD5').
knownkinasetarget('IME2', 'RFA2').
knownkinasetarget('RAD53', 'PTC2').
knownkinasetarget('SNF1', 'HSF1').
knownkinasetarget('TOS3', 'SNF1').
knownkinasetarget('SWE1', 'HSL7').
knownkinasetarget('PHO85', 'PCL1').
knownkinasetarget('HRR25', 'NUP53').
knownkinasetarget('CDC28', 'SLD3').
knownkinasetarget('CDC7', 'DBF4').
knownkinasetarget('CDC28', 'CLN2').
knownkinasetarget('STE11', 'PBS2').
knownkinasetarget('ARK1', 'ABP1').
knownkinasetarget('STE11', 'STE50').
knownkinasetarget('HSL1', 'SWE1').
knownkinasetarget('ATG1', 'ATG13').
knownkinasetarget('CDC28', 'STB1').
knownkinasetarget('CDC28', 'PAH1').
knownkinasetarget('PKC1', 'RHO1').
knownkinasetarget('CHK1', 'PDS1').
knownkinasetarget('CBK1', 'SEC2').
knownkinasetarget('CDC28', 'SAE2').
knownkinasetarget('TPK2', 'YAK1').
knownkinasetarget('CKA1', 'NRG1').
knownkinasetarget('ARK1', 'PAN1').
knownkinasetarget('SWE1', 'CDC5').
knownkinasetarget('CDC5', 'SLK19').
knownkinasetarget('CDC28', 'DBF2').
knownkinasetarget('ARK1', 'SLA1').
knownkinasetarget('IME2', 'NDT80').
knownkinasetarget('PHO85', 'PCL10').
knownkinasetarget('PHO85', 'PCL7').
knownkinasetarget('TOR2', 'YPK2').
knownkinasetarget('HRR25', 'MAM1').
knownkinasetarget('YPK2', 'MYO5').
knownkinasetarget('PRK1', 'ENT1').
knownkinasetarget('PHO85', 'ASH1').
knownkinasetarget('CDC5', 'SAE2').
knownkinasetarget('TPK1', 'RIM15').
knownkinasetarget('CDC5', 'BUB2').
knownkinasetarget('CDC28', 'CLB5').
knownkinasetarget('HRR25', 'TIF6').
knownkinasetarget('FUS3', 'STE5').
knownkinasetarget('RCK2', 'PBS2').
knownkinasetarget('CLA4', 'CDC28').
knownkinasetarget('MEC1', 'RAD9').
knownkinasetarget('PHO85', 'SWI5').
knownkinasetarget('SSN3', 'SSN8').
knownkinasetarget('CBK1', 'TAO3').
knownkinasetarget('CLA4', 'GIC2').
knownkinasetarget('CKA2', 'FPR3').
knownkinasetarget('CKA1', 'SEC63').
knownkinasetarget('CDC28', 'KIP1').
knownkinasetarget('CKA2', 'PUF6').
knownkinasetarget('MEK1', 'RAD54').
knownkinasetarget('CTK1', 'RPS2').
knownkinasetarget('MPS1', 'MOB1').
knownkinasetarget('HRR25', 'IKI3').
knownkinasetarget('HOG1', 'HOT1').
knownkinasetarget('HOG1', 'RPO21').
knownkinasetarget('SGV1', 'BUR2').
knownkinasetarget('CDC28', 'DPB2').
knownkinasetarget('PKH2', 'PKC1').
knownkinasetarget('PKC1', 'PKH2').
knownkinasetarget('IME2', 'GPA2').
knownkinasetarget('RAD53', 'MRC1').
knownkinasetarget('ATG1', 'ATG8').
knownkinasetarget('TPK3', 'ATG13').
knownkinasetarget('TPK2', 'ATG13').
knownkinasetarget('TPK1', 'ATG13').
knownkinasetarget('MPS1', 'MAD1').
knownkinasetarget('SSN3', 'MSN2').
knownkinasetarget('TOR2', 'SLM1').
knownkinasetarget('CDC28', 'SWI5').
knownkinasetarget('PHO85', 'GLC8').
knownkinasetarget('CTK1', 'RPO21').
knownkinasetarget('YAK1', 'CRF1').
knownkinasetarget('SLT2', 'PKC1').
knownkinasetarget('PKC1', 'SLT2').
knownkinasetarget('YGK3', 'BCY1').
knownkinasetarget('SNF1', 'GCN5').
knownkinasetarget('CTK1', 'CTK2').
knownkinasetarget('SNF1', 'ADR1').
knownkinasetarget('CDC28', 'CLB3').
knownkinasetarget('CDC28', 'CLB4').
knownkinasetarget('TPK1', 'CKI1').
knownkinasetarget('PHO85', 'NPA3').
knownkinasetarget('RAD53', 'ASF1').
knownkinasetarget('KIC1', 'SOG2').
knownkinasetarget('SNF1', 'RDS2').
knownkinasetarget('TPK2', 'CIN5').
knownkinasetarget('TPK3', 'CIN5').
knownkinasetarget('TPK1', 'CIN5').
knownkinasetarget('CKA2', 'SPT15').
knownkinasetarget('CKA2', 'CDC37').
knownkinasetarget('SNF1', 'NRG1').
knownkinasetarget('PRK1', 'BNI1').
knownkinasetarget('YAK1', 'HSF1').
knownkinasetarget('DUN1', 'NEJ1').
knownkinasetarget('YCK1', 'MTH1').
knownkinasetarget('YCK1', 'STD1').
knownkinasetarget('HRR25', 'BMH1').
knownkinasetarget('CKA2', 'ELF1').
knownkinasetarget('CKA2', 'SVF1').
knownkinasetarget('CKA1', 'SVF1').
knownkinasetarget('CDC28', 'CDC3').
knownkinasetarget('RAD53', 'HHT2').
knownkinasetarget('HOG1', 'SHO1').
knownkinasetarget('PHO85', 'RIM101').
knownkinasetarget('TOR1', 'RIM15').
knownkinasetarget('RAD53', 'RPH1').
knownkinasetarget('PKC1', 'OPI1').
knownkinasetarget('SGV1', 'RAD6').
knownkinasetarget('TPK2', 'RGT1').
knownkinasetarget('TPK1', 'RGT1').
knownkinasetarget('SLN1', 'SKN7').
knownkinasetarget('IME2', 'SUM1').
knownkinasetarget('SKY1', 'HRB1').
knownkinasetarget('ELM1', 'SWE1').
knownkinasetarget('CDC28', 'ULP2').
knownkinasetarget('HOG1', 'PTP2').
knownkinasetarget('HOG1', 'PTP3').
knownkinasetarget('SLT2', 'SDP1').
knownkinasetarget('SNF1', 'GSY2').
knownkinasetarget('SNF1', 'STD1').
knownkinasetarget('CDC28', 'MIH1').
knownkinasetarget('GIN4', 'CDC3').
knownkinasetarget('CKA2', 'ABF1').
knownkinasetarget('CKA1', 'ABF1').
knownkinasetarget('CKA1', 'FIP1').
knownkinasetarget('CKA2', 'FIP1').
knownkinasetarget('CDC5', 'TUS1').
knownkinasetarget('TOR2', 'GLN3').
knownkinasetarget('PKC1', 'CHS3').
knownkinasetarget('HOG1', 'SWE1').
knownkinasetarget('PBS2', 'NBP2').
knownkinasetarget('RIM15', 'PHO85').
knownkinasetarget('CDC5', 'NUD1').
knownkinasetarget('SLN1', 'SSK1').
knownkinasetarget('PHO85', 'PCL2').
knownkinasetarget('PHO85', 'PCL6').
knownkinasetarget('PHO85', 'PCL9').
knownkinasetarget('PTK2', 'PMA1').
knownkinasetarget('CDC28', 'BNI4').
knownkinasetarget('MRK1', 'BCY1').
knownkinasetarget('CDC28', 'ELM1').
knownkinasetarget('SLT2', 'HOG1').
knownkinasetarget('PKC1', 'MIG1').
knownkinasetarget('KSS1', 'STE7').
knownkinasetarget('SSN3', 'SIP4').
knownkinasetarget('RAD53', 'DBF4').
knownkinasetarget('KIN28', 'TFB3').
knownkinasetarget('ELM1', 'KCC4').
knownkinasetarget('BCK1', 'RLM1').
knownkinasetarget('PHO85', 'WHI5').
knownkinasetarget('PHO85', 'HMS1').
knownkinasetarget('PHO85', 'NCP1').
knownkinasetarget('PSK2', 'UGP1').
knownkinasetarget('TPK2', 'FLO8').
knownkinasetarget('CDC15', 'TEM1').
knownkinasetarget('CLA4', 'GIC1').
knownkinasetarget('CDC28', 'CNM67').
knownkinasetarget('HRR25', 'REC8').
knownkinasetarget('KIN1', 'SEC9').
knownkinasetarget('SNF1', 'PFK27').
knownkinasetarget('HOG1', 'RCK1').
knownkinasetarget('YCK1', 'PTR3').
knownkinasetarget('SLT2', 'YKL161C').
knownkinasetarget('CAK1', 'SMK1').
knownkinasetarget('SSN3', 'GCN4').
knownkinasetarget('SCH9', 'SKO1').
knownkinasetarget('TPK1', 'PFK26').
knownkinasetarget('MCK1', 'HSL1').
knownkinasetarget('ATG1', 'CIS1').
knownkinasetarget('RAD53', 'CDC5').
knownkinasetarget('HRR25', 'ENP1').
knownkinasetarget('FUS3', 'MSG5').
knownkinasetarget('CKA1', 'RIO1').
knownkinasetarget('ATG1', 'ATG18').
knownkinasetarget('RAD53', 'SWE1').
knownkinasetarget('CDC28', 'PHO2').
knownkinasetarget('SNF1', 'ROD1').
knownkinasetarget('SNF1', 'MSN2').
knownkinasetarget('RAD53', 'SLT2').
knownkinasetarget('CDC28', 'CDC14').
knownkinasetarget('CDC28', 'APC9').
knownkinasetarget('SNF1', 'ACC1').
knownkinasetarget('RAD53', 'RFX1').
knownkinasetarget('STE11', 'HOG1').
knownkinasetarget('ATG1', 'ATG9').
knownkinasetarget('HSL1', 'CDC12').
knownkinasetarget('BCK1', 'PKC1').
knownkinasetarget('GIN4', 'HSL1').
knownkinasetarget('MEC1', 'RAD26').
knownkinasetarget('GIN4', 'SWE1').
knownkinasetarget('AKL1', 'SLA1').
knownkinasetarget('SLT2', 'HSP82').
knownkinasetarget('YAK1', 'TPK2').
knownkinasetarget('CDC5', 'RHO1').
knownkinasetarget('SLT2', 'PTP2').
knownkinasetarget('PBS2', 'STE11').
knownkinasetarget('HOG1', 'SRB4').
knownkinasetarget('PRK1', 'YAP1801').
knownkinasetarget('CDC28', 'CLB1').
knownkinasetarget('SNF1', 'CAT8').
knownkinasetarget('KIN4', 'BUB2').
knownkinasetarget('CDC28', 'KIN2').
knownkinasetarget('GIN4', 'KCC4').
knownkinasetarget('CDC28', 'KAR3').
knownkinasetarget('DBF2', 'CDC28').
knownkinasetarget('PKH1', 'YPK2').
knownkinasetarget('SSK22', 'PBS2').
knownkinasetarget('PBS2', 'SSK22').
knownkinasetarget('SSK22', 'SSK1').
knownkinasetarget('RAD53', 'SHS1').
knownkinasetarget('SLT2', 'CNB1').
knownkinasetarget('CDC5', 'PDS5').
knownkinasetarget('CAK1', 'CLN2').
knownkinasetarget('CLA4', 'GIN4').
knownkinasetarget('CDC28', 'SLT2').
knownkinasetarget('CLA4', 'LTE1').
knownkinasetarget('PBS2', 'RCK2').
knownkinasetarget('ELM1', 'HSL1').
knownkinasetarget('SNF1', 'SSN3').
knownkinasetarget('SNF1', 'SSN8').
knownkinasetarget('HAL5', 'RGT1').
knownkinasetarget('HSL1', 'CDC28').
knownkinasetarget('BUD32', 'CGI121').
knownkinasetarget('CTK1', 'CTK3').
knownkinasetarget('RAD53', 'HHT1').
knownkinasetarget('SLT2', 'SLT2').
knownkinasetarget('MEC1', 'CHK1').
knownkinasetarget('MEC1', 'SML1').
knownkinasetarget('RAD53', 'EXO1').
knownkinasetarget('TPK1', 'CDC19').
knownkinasetarget('RIM15', 'YNL157W').
knownkinasetarget('MEC1', 'CBF1').
knownkinasetarget('YCK2', 'PTR3').
knownkinasetarget('KIN82', 'YPK1').
knownkinasetarget('CDC5', 'CDC12').
knownkinasetarget('CKA2', 'CDC28').
knownkinasetarget('SNF1', 'NRG2').
knownkinasetarget('RAD53', 'PIN4').
knownkinasetarget('YAK1', 'TPK1').
knownkinasetarget('KCC4', 'CDC11').
knownkinasetarget('DBF20', 'MOB1').
knownkinasetarget('PRK1', 'BEM2').
knownkinasetarget('MEC1', 'DIF1').
knownkinasetarget('PRK1', 'EDE1').
knownkinasetarget('RCK2', 'EFT1').
knownkinasetarget('RCK2', 'EFT2').
knownkinasetarget('ELM1', 'MIG1').
knownkinasetarget('YCK1', 'MIH1').
knownkinasetarget('YCK2', 'MIH1').
knownkinasetarget('MCK1', 'RCN1').
knownkinasetarget('CDC28', 'REC107').
knownkinasetarget('FUS3', 'RVS167').
knownkinasetarget('CDC5', 'STU2').
knownkinasetarget('RAD53', 'SML1').
knownkinasetarget('MKK1', 'BCK1').
knownkinasetarget('BCK1', 'MKK1').
knownkinasetarget('PRK1', 'SLA2').
knownkinasetarget('RAD53', 'NUP1').
knownkinasetarget('RAD53', 'NUP2').
knownkinasetarget('RAD53', 'NUP60').
knownkinasetarget('CLA4', 'MYO3').
knownkinasetarget('STE20', 'MYO3').
knownkinasetarget('GIN4', 'BNI5').
knownkinasetarget('GIN4', 'CDC10').
knownkinasetarget('MCK1', 'ZDS1').
knownkinasetarget('YKL161C', 'RLM1').
knownkinasetarget('STE20', 'CDC42').
knownkinasetarget('SLT2', 'SMI1').
knownkinasetarget('CDC28', 'CIN8').
knownkinasetarget('PKC1', 'CKI1').
knownkinasetarget('CKA2', 'GAL83').
knownkinasetarget('CDC28', 'MPS1').
knownkinasetarget('CKA1', 'OPI1').
knownkinasetarget('CKA2', 'OPI1').
knownkinasetarget('YCK1', 'PMA1').
knownkinasetarget('YCK2', 'PMA1').
knownkinasetarget('CKA2', 'SGT1').
knownkinasetarget('CKA2', 'SRP1').
knownkinasetarget('CKA1', 'SRP1').
knownkinasetarget('TPK1', 'SSO1').
knownkinasetarget('YCK1', 'STE50').
knownkinasetarget('TPK3', 'SUP35').
knownkinasetarget('TPK2', 'SUP35').
knownkinasetarget('TPK1', 'SUP35').
knownkinasetarget('SNF1', 'GIS4').
knownkinasetarget('TOR1', 'GLN3').
knownkinasetarget('YAK1', 'MSI1').
knownkinasetarget('SNF1', 'SIN4').
knownkinasetarget('TPK2', 'MSN2').
knownkinasetarget('CDC28', 'RTS1').
knownkinasetarget('IRE1', 'GCN5').
knownkinasetarget('PBS2', 'PTC1').
knownkinasetarget('PKC1', 'STT3').
