klocation('AAK1', 'Cytosol', 'MCF7').
klocation('ABL1', 'Cytosol', 'MCF7').
klocation('ABL2', 'Cytosol', 'MCF7').
klocation('ACVR1', 'Secretory', 'MCF7').
klocation('ACVR1B', 'Secretory', 'MCF7').
klocation('ACVR2A', 'Secretory', 'MCF7').
klocation('ACVR2B', 'Secretory', 'MCF7').
klocation('ADCK1', 'Mitochondria', 'MCF7').
klocation('ADCK2', 'Unclassified', 'MCF7').
klocation('ADCK4', 'Mitochondria', 'MCF7').
klocation('ADCK5', 'Mitochondria', 'MCF7').
klocation('ADRBK1', 'Cytosol', 'MCF7').
klocation('AKT1', 'Cytosol', 'MCF7').
klocation('AKT2', 'Cytosol', 'MCF7').
klocation('ARAF', 'Cytosol', 'MCF7').
klocation('ATM', 'Nuclear', 'MCF7').
klocation('ATR', 'Nuclear', 'MCF7').
klocation('AURKA', 'Cytosol', 'MCF7').
klocation('AURKB', 'Nuclear', 'MCF7').
klocation('BCKDK', 'Mitochondria', 'MCF7').
klocation('BCR', 'Cytosol', 'MCF7').
klocation('BMP2K', 'Unclassified', 'MCF7').
klocation('BMPR1A', 'Secretory', 'MCF7').
klocation('BMPR2', 'Secretory', 'MCF7').
klocation('BRAF', 'Cytosol', 'MCF7').
klocation('BRD2', 'Nuclear', 'MCF7').
klocation('BRD3', 'Nuclear', 'MCF7').
klocation('BRD4', 'Nuclear', 'MCF7').
klocation('BRSK2', 'Cytosol', 'MCF7').
klocation('BUB1', 'Cytosol', 'MCF7').
klocation('BUB1B', 'Cytosol', 'MCF7').
klocation('CAMK1', 'Cytosol', 'MCF7').
klocation('CAMK1D', 'Cytosol', 'MCF7').
klocation('CAMK2B', 'Cytosol', 'MCF7').
klocation('CAMK2D', 'Cytosol', 'MCF7').
klocation('CAMK2G', 'Cytosol', 'MCF7').
klocation('CAMKK1', 'Cytosol', 'MCF7').
klocation('CAMKK2', 'Cytosol', 'MCF7').
klocation('CASK', 'Unclassified', 'MCF7').
klocation('CDC42BPA', 'Cytosol', 'MCF7').
klocation('CDC42BPB', 'Cytosol', 'MCF7').
klocation('CDC42BPG', 'Cytosol', 'MCF7').
klocation('CDC7', 'Nuclear', 'MCF7').
klocation('CDK10', 'Unclassified', 'MCF7').
klocation('CDK2', 'Cytosol', 'MCF7').
klocation('CDK4', 'Cytosol', 'MCF7').
klocation('CDK5', 'Cytosol', 'MCF7').
klocation('CDK6', 'Cytosol', 'MCF7').
klocation('CDK7', 'Nuclear', 'MCF7').
klocation('CDK8', 'Nuclear', 'MCF7').
klocation('CDK9', 'Nuclear', 'MCF7').
klocation('CDKL5', 'Nuclear', 'MCF7').
klocation('CHEK1', 'Cytosol', 'MCF7').
klocation('CHEK2', 'Nuclear', 'MCF7').
klocation('CHUK', 'Cytosol', 'MCF7').
klocation('CIT', 'Cytosol', 'MCF7').
klocation('CLK1', 'Nuclear', 'MCF7').
klocation('CLK2', 'Nuclear', 'MCF7').
klocation('CLK3', 'Nuclear', 'MCF7').
klocation('CLK4', 'Nuclear', 'MCF7').
klocation('CSK', 'Cytosol', 'MCF7').
klocation('CSNK1A1', 'Secretory', 'MCF7').
klocation('CSNK1D', 'Nuclear', 'MCF7').
klocation('CSNK1E', 'Secretory', 'MCF7').
klocation('CSNK1G1', 'Cytosol', 'MCF7').
klocation('CSNK1G2', 'Secretory', 'MCF7').
klocation('CSNK1G3', 'Secretory', 'MCF7').
klocation('CSNK2A1', 'Cytosol', 'MCF7').
klocation('CSNK2A2', 'Cytosol', 'MCF7').
klocation('DAPK1', 'Nuclear', 'MCF7').
klocation('DAPK2', 'Unclassified', 'MCF7').
klocation('DAPK3', 'Cytosol', 'MCF7').
klocation('DDR1', 'Secretory', 'MCF7').
klocation('DMPK', 'Cytosol', 'MCF7').
klocation('DYRK1A', 'Cytosol', 'MCF7').
klocation('DYRK1B', 'Cytosol', 'MCF7').
klocation('DYRK2', 'Nuclear', 'MCF7').
klocation('EEF2K', 'Cytosol', 'MCF7').
klocation('EGFR', 'Secretory', 'MCF7').
klocation('EIF2AK1', 'Cytosol', 'MCF7').
klocation('EIF2AK2', 'Nuclear', 'MCF7').
klocation('EIF2AK3', 'Secretory', 'MCF7').
klocation('EIF2AK4', 'Cytosol', 'MCF7').
klocation('EPHA1', 'Secretory', 'MCF7').
klocation('EPHA2', 'Secretory', 'MCF7').
klocation('EPHA3', 'Secretory', 'MCF7').
klocation('EPHA4', 'Secretory', 'MCF7').
klocation('EPHA6', 'Secretory', 'MCF7').
klocation('EPHA7', 'Secretory', 'MCF7').
klocation('EPHB2', 'Secretory', 'MCF7').
klocation('EPHB3', 'Secretory', 'MCF7').
klocation('EPHB4', 'Secretory', 'MCF7').
klocation('ERBB2', 'Secretory', 'MCF7').
klocation('ERBB3', 'Secretory', 'MCF7').
klocation('ERBB4', 'Secretory', 'MCF7').
klocation('ERN1', 'Secretory', 'MCF7').
klocation('FASTK', 'Secretory', 'MCF7').
klocation('FER', 'Cytosol', 'MCF7').
klocation('FGFR1', 'Secretory', 'MCF7').
klocation('FGFR2', 'Secretory', 'MCF7').
klocation('FGFR3', 'Secretory', 'MCF7').
klocation('FGFR4', 'Secretory', 'MCF7').
klocation('FLT1', 'Secretory', 'MCF7').
klocation('FRK', 'Secretory', 'MCF7').
klocation('FYN', 'Secretory', 'MCF7').
klocation('GAK', 'Cytosol', 'MCF7').
klocation('GRK6', 'Secretory', 'MCF7').
klocation('GSG2', 'Nuclear', 'MCF7').
klocation('GSK3A', 'Cytosol', 'MCF7').
klocation('GSK3B', 'Cytosol', 'MCF7').
klocation('HCK', 'Secretory', 'MCF7').
klocation('HIPK1', 'Cytosol', 'MCF7').
klocation('HIPK3', 'Cytosol', 'MCF7').
klocation('HSPB8', 'Cytosol', 'MCF7').
klocation('ICK', 'Unclassified', 'MCF7').
klocation('IGF1R', 'Secretory', 'MCF7').
klocation('IKBKB', 'Cytosol', 'MCF7').
klocation('IKBKE', 'Cytosol', 'MCF7').
klocation('ILK', 'Cytosol', 'MCF7').
klocation('INSR', 'Secretory', 'MCF7').
klocation('IRAK1', 'Cytosol', 'MCF7').
klocation('IRAK4', 'Cytosol', 'MCF7').
klocation('JAK1', 'Secretory', 'MCF7').
klocation('JAK2', 'Secretory', 'MCF7').
klocation('JAK3', 'Nuclear', 'MCF7').
klocation('KALRN', 'Secretory', 'MCF7').
klocation('KSR1', 'Cytosol', 'MCF7').
klocation('LATS1', 'Cytosol', 'MCF7').
klocation('LATS2', 'Cytosol', 'MCF7').
klocation('LIMK1', 'Cytosol', 'MCF7').
klocation('LIMK2', 'Cytosol', 'MCF7').
klocation('LMTK2', 'Secretory', 'MCF7').
klocation('LYN', 'Secretory', 'MCF7').
klocation('MAP2K1', 'Cytosol', 'MCF7').
klocation('MAP2K2', 'Cytosol', 'MCF7').
klocation('MAP2K3', 'Cytosol', 'MCF7').
klocation('MAP2K4', 'Cytosol', 'MCF7').
klocation('MAP2K5', 'Cytosol', 'MCF7').
klocation('MAP2K6', 'Cytosol', 'MCF7').
klocation('MAP2K7', 'Cytosol', 'MCF7').
klocation('MAP3K1', 'Unclassified', 'MCF7').
klocation('MAP3K11', 'Secretory', 'MCF7').
klocation('MAP3K12', 'Secretory', 'MCF7').
klocation('MAP3K2', 'Cytosol', 'MCF7').
klocation('MAP3K3', 'Cytosol', 'MCF7').
klocation('MAP3K4', 'Cytosol', 'MCF7').
klocation('MAP3K5', 'Cytosol', 'MCF7').
klocation('MAP3K6', 'Cytosol', 'MCF7').
klocation('MAP3K7', 'Cytosol', 'MCF7').
klocation('MAP3K9', 'Unclassified', 'MCF7').
klocation('MAP4K2', 'Cytosol', 'MCF7').
klocation('MAP4K3', 'Cytosol', 'MCF7').
klocation('MAP4K4', 'Nuclear', 'MCF7').
klocation('MAP4K5', 'Cytosol', 'MCF7').
klocation('MAPK1', 'Cytosol', 'MCF7').
klocation('MAPK11', 'Cytosol', 'MCF7').
klocation('MAPK12', 'Cytosol', 'MCF7').
klocation('MAPK13', 'Cytosol', 'MCF7').
klocation('MAPK14', 'Cytosol', 'MCF7').
klocation('MAPK15', 'Cytosol', 'MCF7').
klocation('MAPK3', 'Cytosol', 'MCF7').
klocation('MAPK6', 'Cytosol', 'MCF7').
klocation('MAPK7', 'Cytosol', 'MCF7').
klocation('MAPK8', 'Cytosol', 'MCF7').
klocation('MAPK9', 'Cytosol', 'MCF7').
klocation('MAPKAPK2', 'Cytosol', 'MCF7').
klocation('MAPKAPK3', 'Cytosol', 'MCF7').
klocation('MAPKAPK5', 'Cytosol', 'MCF7').
klocation('MARK1', 'Nuclear', 'MCF7').
klocation('MARK2', 'Secretory', 'MCF7').
klocation('MARK3', 'Cytosol', 'MCF7').
klocation('MARK4', 'Cytosol', 'MCF7').
klocation('MAST2', 'Cytosol', 'MCF7').
klocation('MAST3', 'Cytosol', 'MCF7').
klocation('MASTL', 'Nuclear', 'MCF7').
klocation('MATK', 'Cytosol', 'MCF7').
klocation('MELK', 'Cytosol', 'MCF7').
klocation('MERTK', 'Unclassified', 'MCF7').
klocation('MET', 'Secretory', 'MCF7').
klocation('MINK1', 'Nuclear', 'MCF7').
klocation('MKNK1', 'Cytosol', 'MCF7').
klocation('MKNK2', 'Cytosol', 'MCF7').
klocation('MLKL', 'Cytosol', 'MCF7').
klocation('MST1R', 'Secretory', 'MCF7').
klocation('MYLK', 'Cytosol', 'MCF7').
klocation('NEK1', 'Cytosol', 'MCF7').
klocation('NEK11', 'Cytosol', 'MCF7').
klocation('NEK2', 'Secretory', 'MCF7').
klocation('NEK3', 'Cytosol', 'MCF7').
klocation('NEK4', 'Cytosol', 'MCF7').
klocation('NEK6', 'Cytosol', 'MCF7').
klocation('NEK7', 'Cytosol', 'MCF7').
klocation('NEK9', 'Cytosol', 'MCF7').
klocation('NLK', 'Unclassified', 'MCF7').
klocation('NPR1', 'Secretory', 'MCF7').
klocation('NRBP1', 'Cytosol', 'MCF7').
klocation('NRBP2', 'Cytosol', 'MCF7').
klocation('NRK', 'Unclassified', 'MCF7').
klocation('OBSCN', 'Cytosol', 'MCF7').
klocation('OXSR1', 'Cytosol', 'MCF7').
klocation('PAK1', 'Cytosol', 'MCF7').
klocation('PAK2', 'Cytosol', 'MCF7').
klocation('PAK3', 'Cytosol', 'MCF7').
klocation('PAK4', 'Cytosol', 'MCF7').
klocation('PAK6', 'Cytosol', 'MCF7').
klocation('PASK', 'Cytosol', 'MCF7').
klocation('PBK', 'Cytosol', 'MCF7').
klocation('PDIK1L', 'Nuclear', 'MCF7').
klocation('PDK1', 'Mitochondria', 'MCF7').
klocation('PDK2', 'Mitochondria', 'MCF7').
klocation('PDK3', 'Mitochondria', 'MCF7').
klocation('PDPK1', 'Cytosol', 'MCF7').
klocation('PHKG2', 'Cytosol', 'MCF7').
klocation('PIK3R4', 'Cytosol', 'MCF7').
klocation('PKMYT1', 'Secretory', 'MCF7').
klocation('PKN1', 'Cytosol', 'MCF7').
klocation('PKN2', 'Cytosol', 'MCF7').
klocation('PKN3', 'Secretory', 'MCF7').
klocation('PLK1', 'Unclassified', 'MCF7').
klocation('PLK2', 'Secretory', 'MCF7').
klocation('PLK4', 'Unclassified', 'MCF7').
klocation('PRKAA1', 'Cytosol', 'MCF7').
klocation('PRKACA', 'Cytosol', 'MCF7').
klocation('PRKACB', 'Cytosol', 'MCF7').
klocation('PRKACG', 'Cytosol', 'MCF7').
klocation('PRKCA', 'Cytosol', 'MCF7').
klocation('PRKCD', 'Cytosol', 'MCF7').
klocation('PRKCE', 'Cytosol', 'MCF7').
klocation('PRKCH', 'Secretory', 'MCF7').
klocation('PRKCI', 'Cytosol', 'MCF7').
klocation('PRKCZ', 'Cytosol', 'MCF7').
klocation('PRKD1', 'Cytosol', 'MCF7').
klocation('PRKD2', 'Cytosol', 'MCF7').
klocation('PRKD3', 'Cytosol', 'MCF7').
klocation('PRKDC', 'Nuclear', 'MCF7').
klocation('PRKX', 'Cytosol', 'MCF7').
klocation('PRPF4B', 'Nuclear', 'MCF7').
klocation('PSKH1', 'Cytosol', 'MCF7').
klocation('PTK2', 'Cytosol', 'MCF7').
klocation('PTK2B', 'Cytosol', 'MCF7').
klocation('PTK6', 'Cytosol', 'MCF7').
klocation('PTK7', 'Secretory', 'MCF7').
klocation('PXK', 'Cytosol', 'MCF7').
klocation('RAF1', 'Cytosol', 'MCF7').
klocation('RET', 'Secretory', 'MCF7').
klocation('RIOK1', 'Cytosol', 'MCF7').
klocation('RIOK2', 'Cytosol', 'MCF7').
klocation('RIOK3', 'Cytosol', 'MCF7').
klocation('RIPK1', 'Cytosol', 'MCF7').
klocation('RIPK2', 'Cytosol', 'MCF7').
klocation('RIPK4', 'Unclassified', 'MCF7').
klocation('RNASEL', 'Cytosol', 'MCF7').
klocation('ROCK1', 'Cytosol', 'MCF7').
klocation('ROCK2', 'Cytosol', 'MCF7').
klocation('RPS6KA1', 'Cytosol', 'MCF7').
klocation('RPS6KA3', 'Cytosol', 'MCF7').
klocation('RPS6KA4', 'Nuclear', 'MCF7').
klocation('RPS6KA5', 'Nuclear', 'MCF7').
klocation('RPS6KA6', 'Unclassified', 'MCF7').
klocation('RPS6KB1', 'Cytosol', 'MCF7').
klocation('RPS6KB2', 'Cytosol', 'MCF7').
klocation('RPS6KC1', 'Cytosol', 'MCF7').
klocation('RYK', 'Secretory', 'MCF7').
klocation('SCYL1', 'Cytosol', 'MCF7').
klocation('SCYL2', 'Cytosol', 'MCF7').
klocation('SCYL3', 'Unclassified', 'MCF7').
klocation('SLK', 'Cytosol', 'MCF7').
klocation('SMG1', 'Cytosol', 'MCF7').
klocation('SNRK', 'Cytosol', 'MCF7').
klocation('SRC', 'Secretory', 'MCF7').
klocation('SRPK1', 'Nuclear', 'MCF7').
klocation('SRPK2', 'Nuclear', 'MCF7').
klocation('STK10', 'Cytosol', 'MCF7').
klocation('STK11', 'Cytosol', 'MCF7').
klocation('STK16', 'Secretory', 'MCF7').
klocation('STK17A', 'Cytosol', 'MCF7').
klocation('STK17B', 'Cytosol', 'MCF7').
klocation('STK19', 'Unclassified', 'MCF7').
klocation('STK24', 'Cytosol', 'MCF7').
klocation('STK25', 'Cytosol', 'MCF7').
klocation('STK3', 'Cytosol', 'MCF7').
klocation('STK32C', 'Cytosol', 'MCF7').
klocation('STK35', 'Nuclear', 'MCF7').
klocation('STK36', 'Unclassified', 'MCF7').
klocation('STK38', 'Cytosol', 'MCF7').
klocation('STK38L', 'Cytosol', 'MCF7').
klocation('STK39', 'Cytosol', 'MCF7').
klocation('STK4', 'Cytosol', 'MCF7').
klocation('STK40', 'Cytosol', 'MCF7').
klocation('STYK1', 'Nuclear', 'MCF7').
klocation('SYK', 'Cytosol', 'MCF7').
klocation('TAF1', 'Nuclear', 'MCF7').
klocation('TAOK1', 'Cytosol', 'MCF7').
klocation('TAOK2', 'Secretory', 'MCF7').
klocation('TAOK3', 'Cytosol', 'MCF7').
klocation('TBK1', 'Cytosol', 'MCF7').
klocation('TEC', 'Cytosol', 'MCF7').
klocation('TESK1', 'Secretory', 'MCF7').
klocation('TESK2', 'Cytosol', 'MCF7').
klocation('TGFBR1', 'Secretory', 'MCF7').
klocation('TGFBR2', 'Secretory', 'MCF7').
klocation('TLK1', 'Nuclear', 'MCF7').
klocation('TLK2', 'Nuclear', 'MCF7').
klocation('TNIK', 'Cytosol', 'MCF7').
klocation('TNK1', 'Cytosol', 'MCF7').
klocation('TNK2', 'Cytosol', 'MCF7').
klocation('TP53RK', 'Unclassified', 'MCF7').
klocation('TRIB3', 'Nuclear', 'MCF7').
klocation('TRIM24', 'Nuclear', 'MCF7').
klocation('TRIM28', 'Nuclear', 'MCF7').
klocation('TRIM33', 'Nuclear', 'MCF7').
klocation('TRIO', 'Cytosol', 'MCF7').
klocation('TRPM7', 'Secretory', 'MCF7').
klocation('TRRAP', 'Nuclear', 'MCF7').
klocation('TTK', 'Cytosol', 'MCF7').
klocation('TYK2', 'Secretory', 'MCF7').
klocation('TYRO3', 'Secretory', 'MCF7').
klocation('UHMK1', 'Secretory', 'MCF7').
klocation('ULK1', 'Cytosol', 'MCF7').
klocation('ULK3', 'Cytosol', 'MCF7').
klocation('VRK1', 'Nuclear', 'MCF7').
klocation('VRK2', 'Secretory', 'MCF7').
klocation('VRK3', 'Unclassified', 'MCF7').
klocation('WEE1', 'Nuclear', 'MCF7').
klocation('WNK1', 'Cytosol', 'MCF7').
klocation('WNK2', 'Cytosol', 'MCF7').
klocation('YES1', 'Secretory', 'MCF7').
